### ISSUE TITLE
Remove inline script

### ISSUE THREAD

**Issue by rodfersou** [collective/covertile.cycle2#7] opened 2015-05-15 12:20 UTC
If you add the cycle-slideshow class here https://github.com/collective/covertile.cycle2/blob/master/src/covertile/cycle2/tiles/templates/carousel.pt#L68 you will not need to add the inline script here https://github.com/collective/covertile.cycle2/blob/master/src/covertile/cycle2/tiles/templates/carousel.pt#L68

it just don't work if the html is loaded by some ajax call.. in this case you need to make the `$( '.covertile-cycle2' ).cycle();` call when the ajax finish

Inline scripts are a PITA when you need to make a code that pass into acessibility checkers..

If this case really need to have this javascript, I suggest to move it into a registered separated javascript file.

**Comment by djowett** [comment] 2015-05-19 13:07
It was a deliberate choice to activate by AJAX call rather than by class, but it was a 7 months ago & I can't remember why, so don't know whether the reason applies now.

Small Inline scripts aren't a bad thing.  (and I intend to keep it small)  Can you provide an example of a PITA accessiblity checker running on this? ;-)

**Comment by rodfersou** [comment] 2015-05-19 13:43
@djowett the accessibility checkers ask for the task <noscript> with the "alternative" content of the script tag..

But in this case there is no alternative content, and the script should not be inline, it deserves a .js file for it

**Comment by hvelarde** [comment] 2015-05-19 15:22
@djowett I found this one: http://www.powermapper.com/products/sortsite/ads/acc-wcag-testing.htm

maybe @polyester knows another.

**Comment by polyester** [comment] 2015-05-19 15:27
http://wave.webaim.org and their Chrome/Firefox extensions are good. Slightly pedantic, but good. And scriptable/robottestable...

**Comment by djowett** [comment] 2015-05-19 15:37
thanks @polyester - is it true that inline Javascript is bad? (even 1 line?)

**Comment by polyester** [comment] 2015-05-19 15:41
No, not at all. Just things like
- images without alt
- 'popups' without reachable, tabbing close button/link
- loss of focus that is not announced/transmitted to screenreaders. (or the classic "click outside the lightboxed image to get back" for visual impaired readers...)

or in short, non-a11y javascript is bad...

**Comment by polyester** [comment] 2015-05-19 15:48
I'm not 100% sure I fully get what the original idea was, but if you have purely 'decorative' images, with no sensible alt-tag, it is perfectly fine to mark it with an empty alt-tag, btw. But the tag has to be there. http://www.w3.org/WAI/tutorials/images/decorative

**Comment by rodfersou** [comment] 2015-05-20 12:04
@djowett @polyester @hvelarde in fact, inline scripts could be harmless and we (people) know when it is and when it is not.

But automated accessibility checkers are not as intelligent as we are, so I prefer to keep the layout without inline scripts when possible.

**Comment by rodfersou** [comment] 2015-05-20 12:07
@felipeduardo could add some words about it too.

**Comment by djowett** [comment] 2015-05-20 12:08
Ok, thanks for acknowledging the point.

As I said I was wary of removing the script as there was a reason for it 
being there,
but since I'm not yet using this in production, I'll make the change & 
we can revert it if problems
come up.  Though do let us know here if you see any problems in 
collective.nitf ...

On 20/05/15 13:04, Rodrigo Ferreira de Souza wrote:

> @djowett https://github.com/djowett @polyester 
> https://github.com/polyester @hvelarde https://github.com/hvelarde 
> in fact, inline scripts could be harmless and we (people) know when it 
> is and when it is not.
> 
> But automated accessibility checkers are not as intelligent as we are, 
> so I prefer to keep the layout without inline scripts when possible.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/collective/covertile.cycle2/issues/7#issuecomment-103859190.

## 

Daniel Jowett

_Jowett Enterprises Ltd_
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by rodfersou** [comment] 2015-05-20 12:16
:+1:

**Comment by djowett** [comment] 2015-05-20 16:05
Hi @rodfersou, 

I tried what you suggested, but I have the following regression:

When I'm on the Compose view & I try to drag an image in to the Carousel, the Carousel goes blank until I reload the page.  

I can't explain why, can you?

I'm inclined to leave the code as is... 
(I don't like the separate Javascript file idea - that adds in an extra HTTP request, and accessibility checker warnings aren't the end of the world IMMO - if your accessibility checks are clean apart from this one line, then I'm v impressed! )

**Comment by djowett** [comment] 2015-05-22 09:42
I'm closing this off without action, based on the following thinking (my summary of some statements above):
- Inline scripts aren't bad
- Accessibility checkers reporting Inline Scripts need to grow up (IMO) 
- Trying removing the Inline script in this instance leads to a regression on the Compose view
- A separate JS file for this one line will add an extra HTTP request, plus is harder to maintain
- We plan to keep this Inline JS very simple

Any objections - please post back

**Closed as completed by djowett** 2015-05-22 09:42 UTC
Labels: question

**Comment by hvelarde** [comment] 2015-05-22 11:07
in fact, I think you must just add the `.cycle-slideshow` style to the tile container and just get rid of the script completely because is not necessary.

**Comment by djowett** [comment] 2015-05-22 11:51
@hvelarde I tried that but it had a regression as I mentioned in [a comment above](https://github.com/collective/covertile.cycle2/issues/7#issuecomment-103941165)

**Comment by rodfersou** [comment] 2015-05-22 13:01
@djowett I think you need to add a callback to the event listener after drop element to start cycle2 when you have this tile.

**Comment by djowett** [comment] 2015-05-22 13:04
@rodfersou do you want to make a pull request to demonstrate? :-)

**Comment by rodfersou** [comment] 2015-05-22 20:33
@djowett I'll try this weekend
